apiVersion: apps/v1
kind: Deployment
metadata:
  name: efefic-u2-api-gateway
  namespace: efefic-fdvp20261-u2
  labels:
    app: efefic-u2-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efefic-u2-api-gateway
  template:
    metadata:
      labels:
        app: efefic-u2-api-gateway
    spec:
      containers:
      - name: efefic-u2-api-gateway
        # Esta imagen es la base, Jenkins la actualizará con el número de build
        image: docker.io/juliandc17/efefic-u2-api-gateway:latest
        ports:
        - containerPort: 8080
        # Opcional: Readiness probe para asegurar que el Smoke Test no falle por rapidez
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: efefic-u2-api-gateway
  namespace: efefic-fdvp20261-u2
spec:
  type: LoadBalancer
  selector:
    app: efefic-u2-api-gateway
  ports:
    - protocol: TCP
      port: 80         # Puerto externo en tu localhost (http://localhost)
      targetPort: 8080 # Puerto interno de tu aplicación FastAPI