apiVersion: apps/v1
kind: Deployment
metadata:
  name: efefic-u2-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efefic-u2-api-gateway
  template:
    metadata:
      labels:
        app: efefic-u2-api-gateway
    spec:
      containers:
      - name: efefic-u2-api-gateway
        image: juliandc17/efefic-u2-api-gateway:latest
        ports:
        - containerPort: 8080 # Puerto interno de la app
---
apiVersion: v1
kind: Service
metadata:
  name: efefic-u2-api-gateway
spec:
  type: LoadBalancer
  selector:
    app: efefic-u2-api-gateway
  ports:
    - protocol: TCP
      port: 80         # Puerto externo (Pruébalo así para evitar conflictos con Jenkins)
      targetPort: 8080 # Puerto interno (El que usa tu app FastAPI/Python)