apiVersion: apps/v1
kind: Deployment
metadata:
  name: efefic-u2-api-gateway
  namespace: efefic-fdvp20261-u2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efefic-u2-api-gateway
  template:
    metadata:
      labels:
        app: efefic-u2-api-gateway
    spec:
      containers:
      - name: efefic-u2-api-gateway
        image: docker.io/juliandc17/efefic-u2-api-gateway:latest
        ports:
        - containerPort: 8000 # <--- ASEGÚRATE DE QUE ESTE SEA EL PUERTO DE TU DOCKERFILE
        readinessProbe:
          httpGet:
            path: /health
            port: 8000 # <--- DEBE COINCIDIR CON EL CONTAINER PORT
          initialDelaySeconds: 10 # Damos más tiempo para arrancar
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: efefic-u2-api-gateway
  namespace: efefic-fdvp20261-u2
spec:
  type: LoadBalancer
  selector:
    app: efefic-u2-api-gateway
  ports:
    - protocol: TCP
      port: 80         # Puerto externo (PC)
      targetPort: 8000 # <--- DEBE COINCIDIR CON EL CONTAINER PORT